service: sharp-layer
frameworkVersion: '3'

provider:
  name: aws
  region: ap-southeast-2
  stage: prod

layers:
  sharp-0_33_5-node-20:
    path: build
    compatibleRuntimes:
      - nodejs20.x
    compatibleArchitectures:
      - x86_64
    allowedAccounts:
      - '*'
