name: Deploy API

on:
  push:
    branches:
      - main

concurrency: deploy-api

jobs:
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Restore Yarn cache
        uses: actions/cache@v2
        with:
          path: ./api/node_modules
          key: api-yarn-${{ hashFiles('./app/yarn.lock') }}
          restore-keys: api-yarn-
      - name: Retrieve AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        run: make api/deploy STAGE=staging
