name: Deploy Client

on:
  push:
    branches:
      - develop
    paths:
      - 'client/**'
      - Makefile
      - .github/workflows/deploy-client-staging.yml

permissions:
      id-token: write
      contents: read

concurrency: deploy-client-staging

jobs:
  deploy-staging:
    name: Deploy staging
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Restore Yarn cache
        uses: actions/cache@v2
        with:
          path: ./client/node_modules
          key: client-yarn-${{ hashFiles('./client/yarn.lock') }}
          restore-keys: client-yarn-
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ap-southeast-2
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      - name: Deploy
        run: make client/deploy STAGE=staging
